spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: bgman365491YZX#
  #
  servlet:
    multipart:
      max-file-size: 500MB      #单个文件大小
      max-request-size: 500MB

mybatis:
  type-aliases-packages:
    - com.example.bs.entity
    - com.example.bs.core
  mapper-locations: classpath:mapper/*xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8084